export const brief = [
  {
    id: 1,
    question: 'Name your brief.',
    help: {},
    description: '',
    content: {},
  },
  {
    id: 2,
    question: 'Who will fill out the brief ?',
    help: {},
    description: '',
    content: {},
  },
  {
    id: 3,
    question: 'Please select the brand’s primary industry.',
    help: {},
    description: 'Select 1 option',
    content: {
      options: [
        'Arts & Crafts',
        'Baby care & Toys',
        'Beauty',
        'Book & Print',
        'Clothing & Accessories',
        'Computers & Electronics',
        'Environmental',
        'Financial Services',
        'Food & Beverage',
        'Hobbies & Leisure',
        'Government & Non-Profit',
        'Health',
        'Home & Garden',
        'Industrial',
        'Education',
        'Media & Entertainment',
        'Pets & Animals',
        'Proffesional Services',
        'Real Estate',
        'Sports & Fitness',
        'Travel & Lifestyle',
      ],
    },
  },
  {
    id: 4,
    question: 'Describe the product or service.',
    help: {},
    description: '',
    content: {},
  },
  {
    id: 5,
    question: 'What type of project do you want ?',
    help: {},
    description: 'Select at least 1 option',
    content: {
      options: ['Design', 'Development', 'Maintenance', 'All'],
    },
  },
  {
    id: 6,
    question: 'Select a design project type.',
    help: {},
    description: 'Select at least 1 option',
    content: {
      options: [
        'Logo',
        'Stationary',
        'Website',
        'Brochure / Flyer',
        'Mobile App',
        'Packaging',
      ],
    },
  },
  {
    id: 7,
    question: 'Is this a new design or a redesign ?',
    help: {},
    description: 'Select at least 1 option',
    content: {
      options: ['new', 'redesign'],
    },
  },
  {
    id: 8,
    question: 'Which level of design would you like for your application ?',
    help: {},
    description: 'Select at least 1 option',
    content: {
      options: [
        'Simple template',
        'Complex custom',
        'Awwwards level',
        'Not sure',
      ],
    },
  },
  {
    id: 9,
    question: 'Select a design direction for this website.',
    help: {},
    description:
      'A design direction vissualy communicates the look and feel for the project. (learn more)',
    content: {
      options: [],
    },
  },
  {
    id: 10,
    question: 'Create an image collage to showcase the project’s look & feel.',
    help: {},
    description:
      'The images should reflect your project’s ambiance, rather than the subject matter itself. Generate random images. Look the ones you find appropriate or load new ones.',
    content: {},
  },
  {
    id: 11,
    question: 'What’s the state of your application ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: [
        'I have a basic idea of what I want to build.',
        'I have a solid idea of what I want to build but I need to define some specific features.',
        'I have the specification for every feature of the app ready but some things could change during the creating process.',
        'I’m sure of what I want and nothing will change during the creating process.',
      ],
    },
  },
  {
    id: 12,
    question: 'How big is your application ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: ['Small', 'Medium', 'Large'],
    },
  },
  {
    id: 13,
    question: 'What platforms are you planning to develop your app in ?',
    help: {},
    description: 'Select as many options as you need.',
    content: {
      options: ['Android', 'iOS', 'Web', 'All'],
    },
  },
  {
    id: 14,
    question: 'Which key functionalities stand the website have ?',
    help: {},
    description: 'Select as many options as you need.',
    content: {
      options: [
        'Newsletter sign up',
        'Blog',
        'Contact form',
        'Facebook connect',
        'Newsletter sign up',
        'Social share buttons',
        'Testimonials',
        'Online shop',
        'Media gallery',
        'Member directory',
        'Portfolio showcase',
        'Events Calendar',
      ],
    },
  },
  {
    id: 15,
    question:
      'What do you expect the audience to do on your website ? (calls to action)',
    help: {},
    description: 'Select as many options as you need.',
    content: {
      options: [
        'Email us',
        'Call us',
        'Buy a product',
        'Subscribe',
        'Register for a trial',
        'Make a donation',
        'Subscribe to a newsletter',
        'Read editorial content',
        'Download content',
        'Refer a friend',
        'All',
        '+',
      ],
    },
  },
  {
    id: 16,
    question:
      'In which language(s) does the brand communicate with its audience ?',
    help: {},
    description: 'Select as many options as you need.',
    content: {
      options: [
        'English(US)',
        'English(UK)',
        'French',
        'German',
        'Italien',
        'Japanese',
        'Mandarin',
        'Russian',
        'Spanish',
        'All',
        '+',
      ],
    },
  },
  {
    id: 17,
    question: 'Which level of animation would you like for your application ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: ['Basic', 'Enhanced', 'Gaming', 'Not sure'],
    },
  },
  {
    id: 18,
    question: 'What type of content will be used in this website ?',
    help: {},
    description: 'Select as many options as you need.',
    content: {
      options: [
        'Text',
        'Photos',
        'Videos',
        'Downloadable documents',
        'Graphic design elements',
        'Illustrations',
        'All',
        '+',
      ],
    },
  },
  {
    id: 19,
    question: 'Is content ready ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: [
        'Yes, done',
        'Working on it',
        'Looking for content provider',
        'No',
        '+',
      ],
    },
  },
  {
    id: 20,
    question: 'Upload additional files.',
    help: {},
    description:
      'Please upload any additional brand assets, screenshoots or files you’d like to attach to this brief.',
    content: {},
  },
  {
    id: 21,
    question: 'What is the deadline for this project ?',
    help: {},
    description: '',
    content: {},
  },
  {
    id: 22,
    question: 'How soon would you like your project to start ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: [
        'Less than 2 months.',
        'Less than 1 month.',
        'Less than 2 weeks.',
        'Less than 1 week',
        'It’s already begun',
        'Not sure.',
      ],
    },
  },
  {
    id: 23,
    question: 'Do you need a local web designer ?',
    help: {},
    description:
      'Select at least 1 option. Note, you will receive more and possible lower cost quotes if you you can work via email and online.',
    content: {
      options: [
        'No, I can work via email, online and phone conversation.',
        'Yes, I need o meet the designer face to face.',
        'Not sure.',
      ],
    },
  },
  {
    id: 24,
    question: 'How much experience do you have building applications  ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: [
        'I have never been involved in this process before.',
        'I have basic knowledge in the process of creating applications.',
        'I’m an expert in building applications.',
      ],
    },
  },
  {
    id: 25,
    question: 'How much time will the client be available for the team  ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {},
  },
  {
    id: 26,
    question: 'What is the budget for this project ?',
    help: {},
    description: 'Select at least 1 option.',
    content: {
      options: [
        '€ 0-500',
        '€ 500-1000',
        '€ 1000-2000',
        '€ 2000-5000',
        '€ 5000-10000',
        '€ 10000-20000',
        '€ 20000-40000',
        '€ +40000',
        '+',
      ],
    },
  },
];
